slam_toolbox:
  ros__parameters: 
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping

    max_laser_range: 30.0
    
#    minimum_travel_distance: 0.005
#    minimum_travel_heading: 0.01
#    minimum_time_interval: 0.02

#Extremely aggressive, for testing only
    minimum_travel_distance: 0.0
    minimum_travel_heading: 0.0
    minimum_time_interval: 0.0

    loop_search_maximum_distance: 10.0
    correlation_search_space_dimension: 0.8
    loop_search_minimum_response_coarse: 0.12

    solver_plugin: solver_plugins::CeresSolver
    ceres_loss_function: HuberLoss
    use_scan_matching: true
    use_scan_barycenter: true

    map_update_interval: 0.1
    scan_queue_size: 80

    tf_buffer_duration: 60.0
    transform_tolerance: 1.0
    transform_publish_period: 0.01

    debug_logging: true
    enable_interactive_mode: true
